In [8]:
from sklearn.impute import KNNImputer
import pandas as pd

In [3]:
df = pd.read_csv('/content/hcvdat0.csv')

In [4]:
df.head()

,Unnamed: 0,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,1,0=Blood Donor,32,m,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,2,0=Blood Donor,32,m,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,3,0=Blood Donor,32,m,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3
3,4,0=Blood Donor,32,m,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7
4,5,0=Blood Donor,32,m,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  615 non-null    int64
 1   Category    615 non-null    object
 2   Age         615 non-null    int64
 3   Sex         615 non-null    object
 4   ALB         614 non-null    float64
 5   ALP         597 non-null    float64
 6   ALT         614 non-null    float64
 7   AST         615 non-null    float64
 8   BIL         615 non-null    float64
 9   CHE         615 non-null    float64
 10  CHOL        605 non-null    float64
 11  CREA        615 non-null    float64
 12  GGT         615 non-null    float64
 13  PROT        614 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 67.4+ KB

In [6]:
df.describe()

,Unnamed: 0,Age,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
count,615.000000,615.000000,614.000000,597.000000,614.000000,615.000000,615.000000,615.000000,605.000000,615.000000,615.000000,614.000000
mean,308.000000,47.408130,41.620195,68.283920,28.450814,34.786341,11.396748,8.196634,5.368099,81.287805,39.533171,72.044137
std,177.679487,10.055105,5.780629,26.028315,25.469689,33.090690,19.673150,2.205657,1.132728,49.756166,54.661071,5.402636
min,1.000000,19.000000,14.900000,11.300000,0.900000,10.600000,0.800000,1.420000,1.430000,8.000000,4.500000,44.800000
25%,154.500000,39.000000,38.800000,52.500000,16.400000,21.600000,5.300000,6.935000,4.610000,67.000000,15.700000,69.300000
50%,308.000000,47.000000,41.950000,66.200000,23.000000,25.900000,7.300000,8.260000,5.300000,77.000000,23.300000,72.200000
75%,461.500000,54.000000,45.200000,80.100000,33.075000,32.900000,11.200000,9.590000,6.060000,88.000000,40.200000,75.400000
max,615.000000,77.000000,82.200000,416.600000,325.300000,324.000000,254.000000,16.410000,9.670000,1079.100000,650.900000,90.000000

In [7]:
df.isnull().sum()

Unnamed: 0     0
Category       0
Age            0
Sex            0
ALB            1
ALP           18
ALT            1
AST            0
BIL            0
CHE            0
CHOL          10
CREA           0
GGT            0
PROT           1
dtype: int64

In [11]:
df_encoded = pd.get_dummies(df)

In [12]:
df_encoded

,Unnamed: 0,Age,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Category_0=Blood Donor,Category_0s=suspect Blood Donor,Category_1=Hepatitis,Category_2=Fibrosis,Category_3=Cirrhosis,Sex_f,Sex_m
0,1,32,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,True,False,False,False,False,False,True
1,2,32,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,True,False,False,False,False,False,True
2,3,32,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,True,False,False,False,False,False,True
3,4,32,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,True,False,False,False,False,False,True
4,5,32,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,611,62,32.0,416.6,5.9,110.3,50.0,5.57,6.30,55.7,650.9,68.5,False,False,False,False,True,True,False
611,612,64,24.0,102.8,2.9,44.4,20.0,1.54,3.02,63.0,35.9,71.3,False,False,False,False,True,True,False
612,613,64,29.0,87.3,3.5,99.0,48.0,1.66,3.63,66.7,64.2,82.0,False,False,False,False,True,True,False
613,614,46,33.0,NaN,39.0,62.0,20.0,3.56,4.20,52.0,50.0,71.0,False,False,False,False,True,True,False
614,615,59,36.0,NaN,100.0,80.0,12.0,9.07,5.30,67.0,34.0,68.0,False,False,False,False,True,True,False

In [13]:
imputer = KNNImputer(n_neighbors=5)

In [14]:
df_imputed = pd.DataFrame(imputer.fit_transform(df_encoded), columns=df_encoded.columns)

In [15]:
df_imputed

,Unnamed: 0,Age,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Category_0=Blood Donor,Category_0s=suspect Blood Donor,Category_1=Hepatitis,Category_2=Fibrosis,Category_3=Cirrhosis,Sex_f,Sex_m
0,1.0,32.0,38.5,52.50,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2.0,32.0,38.5,70.30,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3.0,32.0,46.9,74.70,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4.0,32.0,43.2,52.00,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5.0,32.0,39.2,74.10,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,611.0,62.0,32.0,416.60,5.9,110.3,50.0,5.57,6.30,55.7,650.9,68.5,0.0,0.0,0.0,0.0,1.0,1.0,0.0
611,612.0,64.0,24.0,102.80,2.9,44.4,20.0,1.54,3.02,63.0,35.9,71.3,0.0,0.0,0.0,0.0,1.0,1.0,0.0
612,613.0,64.0,29.0,87.30,3.5,99.0,48.0,1.66,3.63,66.7,64.2,82.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
613,614.0,46.0,33.0,48.42,39.0,62.0,20.0,3.56,4.20,52.0,50.0,71.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
614,615.0,59.0,36.0,40.64,100.0,80.0,12.0,9.07,5.30,67.0,34.0,68.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [16]:
df_imputed.isnull().sum()

Unnamed: 0                         0
Age                                0
ALB                                0
ALP                                0
ALT                                0
AST                                0
BIL                                0
CHE                                0
CHOL                               0
CREA                               0
GGT                                0
PROT                               0
Category_0=Blood Donor             0
Category_0s=suspect Blood Donor    0
Category_1=Hepatitis               0
Category_2=Fibrosis                0
Category_3=Cirrhosis               0
Sex_f                              0
Sex_m                              0
dtype: int64

In [22]:
#######################

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_csv('/content/hcvdat0.csv')

In [23]:
df.head(5)

,Unnamed: 0,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,1,0=Blood Donor,32,m,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,2,0=Blood Donor,32,m,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,3,0=Blood Donor,32,m,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3
3,4,0=Blood Donor,32,m,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7
4,5,0=Blood Donor,32,m,39.2,74.1,32.6,24.8,9.6,9.15,4.32,76.0,29.9,68.7

In [24]:
df.shape

(615, 14)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  615 non-null    int64
 1   Category    615 non-null    object
 2   Age         615 non-null    int64
 3   Sex         615 non-null    object
 4   ALB         614 non-null    float64
 5   ALP         597 non-null    float64
 6   ALT         614 non-null    float64
 7   AST         615 non-null    float64
 8   BIL         615 non-null    float64
 9   CHE         615 non-null    float64
 10  CHOL        605 non-null    float64
 11  CREA        615 non-null    float64
 12  GGT         615 non-null    float64
 13  PROT        614 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 67.4+ KB

In [27]:
df.isnull().sum()

Unnamed: 0     0
Category       0
Age            0
Sex            0
ALB            1
ALP           18
ALT            1
AST            0
BIL            0
CHE            0
CHOL          10
CREA           0
GGT            0
PROT           1
dtype: int64

In [28]:
df=df.dropna()
df.isna().sum()

Unnamed: 0    0
Category      0
Age           0
Sex           0
ALB           0
ALP           0
ALT           0
AST           0
BIL           0
CHE           0
CHOL          0
CREA          0
GGT           0
PROT          0
dtype: int64

In [29]:
df.shape

(589, 14)

In [31]:
df.head(4)

,Unnamed: 0,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,1,0=Blood Donor,32,m,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,2,0=Blood Donor,32,m,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,3,0=Blood Donor,32,m,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3
3,4,0=Blood Donor,32,m,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7

In [32]:
df.drop('Unnamed: 0',axis=1,inplace=True)

<ipython-input-32-f874ac6189f6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Unnamed: 0',axis=1,inplace=True)

In [33]:
df.head(3)

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,0=Blood Donor,32,m,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,0=Blood Donor,32,m,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,0=Blood Donor,32,m,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3

In [34]:
df.Sex.replace(('m','f'),(0,1),inplace=True)

<ipython-input-34-ea3eaeff15b1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Sex.replace(('m','f'),(0,1),inplace=True)
<ipython-input-34-ea3eaeff15b1>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.Sex.replace(('m','f'),(0,1),inplace=True)
<ipython-input-34-ea3eaeff15b1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Sex.replace(('m','f'),(0,1),inplace=True)

In [35]:
df.head(3)

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,0=Blood Donor,32,0,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,0=Blood Donor,32,0,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,0=Blood Donor,32,0,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3

In [36]:
df['Category'].value_counts()

Category
0=Blood Donor             526
3=Cirrhosis                24
1=Hepatitis                20
2=Fibrosis                 12
0s=suspect Blood Donor      7
Name: count, dtype: int64

In [37]:
df['Category']=[0 if i=="0=Blood Donor" or i=="0s=suspect Blood Donor" else 1
if i=="1=Hepatitis" else  2 if i=="2=Fibrosis" else 3 for i in df['Category']]

<ipython-input-37-a9fc5e853acd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category']=[0 if i=="0=Blood Donor" or i=="0s=suspect Blood Donor" else 1

In [38]:
df['Category'].value_counts()

Category
0    533
3     24
1     20
2     12
Name: count, dtype: int64

In [39]:
df.head(4)

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
0,0,32,0,38.5,52.5,7.7,22.1,7.5,6.93,3.23,106.0,12.1,69.0
1,0,32,0,38.5,70.3,18.0,24.7,3.9,11.17,4.80,74.0,15.6,76.5
2,0,32,0,46.9,74.7,36.2,52.6,6.1,8.84,5.20,86.0,33.2,79.3
3,0,32,0,43.2,52.0,30.6,22.6,18.9,7.33,4.74,80.0,33.8,75.7

In [40]:
df.corr()

,Category,Age,Sex,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT
Category,1.000000,0.106264,-0.044617,-0.276111,0.053745,-0.198341,0.628535,0.549021,-0.369752,-0.283626,0.243989,0.424393,-0.039483
Age,0.106264,1.000000,0.014288,-0.191094,0.177720,-0.040576,0.072739,0.039655,-0.075863,0.124742,-0.025142,0.143379,-0.159760
Sex,-0.044617,0.014288,1.000000,-0.150091,0.007601,-0.177107,-0.129883,-0.108063,-0.181649,0.030447,-0.158068,-0.128142,-0.043296
ALB,-0.276111,-0.191094,-0.150091,1.000000,-0.146120,0.039497,-0.177609,-0.169597,0.360919,0.210420,0.001433,-0.147598,0.570726
ALP,0.053745,0.177720,0.007601,-0.146120,1.000000,0.221603,0.067024,0.058372,0.029482,0.125900,0.153909,0.461300,-0.063085
ALT,-0.198341,-0.040576,-0.177107,0.039497,0.221603,1.000000,0.198658,-0.106797,0.224344,0.149997,-0.036106,0.219707,0.016786
AST,0.628535,0.072739,-0.129883,-0.177609,0.067024,0.198658,1.000000,0.309580,-0.197270,-0.201213,-0.017948,0.477774,0.017404
BIL,0.549021,0.039655,-0.108063,-0.169597,0.058372,-0.106797,0.309580,1.000000,-0.320713,-0.181570,0.019910,0.210567,-0.052575
CHE,-0.369752,-0.075863,-0.181649,0.360919,0.029482,0.224344,-0.197270,-0.320713,1.000000,0.428018,-0.012120,-0.095716,0.306288
CHOL,-0.283626,0.124742,0.030447,0.210420,0.125900,0.149997,-0.201213,-0.181570,0.428018,1.000000,-0.051464,0.008823,0.245050
CREA,0.243989,-0.025142,-0.158068,0.001433,0.153909,-0.036106,-0.017948,0.019910,-0.012120,-0.051464,1.000000,0.125353,-0.030111
GGT,0.424393,0.143379,-0.128142,-0.147598,0.461300,0.219707,0.477774,0.210567,-0.095716,0.008823,0.125353,1.000000,-0.037127
PROT,-0.039483,-0.159760,-0.043296,0.570726,-0.063085,0.016786,0.017404,-0.052575,0.306288,0.245050,-0.030111,-0.037127,1.000000

In [41]:
from sklearn.model_selection import train_test_split

X=df.drop("Category",axis=1)
y=df['Category']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [44]:
#Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

Mean Squared Error (MSE): 0.13
R-squared (R2): 0.77

In [45]:
#Linear Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

Accuracy: 0.93
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       128
           1       0.50      0.38      0.43         8
           2       0.33      0.50      0.40         4
           3       0.75      0.75      0.75         8

    accuracy                           0.93       148
   macro avg       0.64      0.65      0.64       148
weighted avg       0.93      0.93      0.93       148

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [46]:
#Decision Trees
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

model = DecisionTreeClassifier() # [2]
model.fit(X_train, y_train) # [2]
y_pred = model.predict(X_test) # [2]

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

Accuracy: 0.91
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.98      0.97       128
           1       0.33      0.25      0.29         8
           2       0.40      0.50      0.44         4
           3       0.75      0.75      0.75         8

    accuracy                           0.91       148
   macro avg       0.61      0.62      0.61       148
weighted avg       0.91      0.91      0.91       148

In [47]:
#SVM
from sklearn import svm
from sklearn.metrics import accuracy_score, classification_report

model = svm.SVC(kernel='linear') # Linear Kernel

model.fit(X_train, y_train) # [2]
y_pred = model.predict(X_test) # [2]

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

Accuracy: 0.94
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       128
           1       0.60      0.38      0.46         8
           2       0.22      0.50      0.31         4
           3       1.00      0.75      0.86         8

    accuracy                           0.94       148
   macro avg       0.71      0.66      0.66       148
weighted avg       0.96      0.94      0.94       148

In [48]:
#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

Accuracy: 0.91
Classification Report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.97       128
           1       0.00      0.00      0.00         8
           2       0.50      0.50      0.50         4
           3       1.00      0.62      0.77         8

    accuracy                           0.91       148
   macro avg       0.61      0.53      0.56       148
weighted avg       0.89      0.91      0.90       148

In [49]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

model = GaussianNB()
model.fit(X_train, y_train) # [1, 2]
y_pred = model.predict(X_test) # [1, 2]

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

Accuracy: 0.91
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96       128
           1       0.00      0.00      0.00         8
           2       0.57      1.00      0.73         4
           3       0.78      0.88      0.82         8

    accuracy                           0.91       148
   macro avg       0.58      0.71      0.63       148
weighted avg       0.88      0.91      0.89       148

In [50]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Create a Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42) # You can adjust n_estimators

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

Accuracy: 0.92
Classification Report:
               precision    recall  f1-score   support

           0       0.93      1.00      0.97       128
           1       0.25      0.12      0.17         8
           2       1.00      0.25      0.40         4
           3       1.00      0.75      0.86         8

    accuracy                           0.92       148
   macro avg       0.80      0.53      0.60       148
weighted avg       0.90      0.92      0.90       148